<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Html Generated</title>
    <meta name="description" content="Figma htmlGenerator">
    <meta name="author" content="htmlGenerator">
    <link href="https://fonts.googleapis.com/css?family=KyivType+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

    <style>
        .e228_549 {
            overflow: hidden;
        }

        .e228_549 {
            width: 100%;
            height: 1190px;
            position: absolute;
            background-image: linear-gradient(
                    0deg, rgba(254.00000005960464, 109.00000110268593, 116.00000068545341, 1) 0%, rgba(254.00000005960464, 109.00000110268593, 116.00000068545341, 1) 0.009999999747378752%, rgba(218.87500405311584, 157.77239799499512, 160.72217971086502, 1) 100%, rgba(218.87500405311584, 157.77239799499512, 160.72217971086502, 1) 100%);
        }

        .e228_550 {
            width: 100%;
            height: 2500px;
            position: absolute;
        }

        .e228_565 {
            width: 583px;
            height: 574px;
            position: absolute;
            left: -158px;
            top: -318px;
        }

        .e228_566 {
            width: 908px;
            height: 894px;
            position: absolute;
            left: 1185px;
            top: 197px;
            background-image: url("/images/curves4_2.png");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_567 {
            transform: rotate(-164.76853003393214deg);
            width: 908px;
            height: 894px;
            position: absolute;
            left: 350px;
            top: 850px;
            background-image: url("/images/curves4_3.png");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_568 {
            transform: rotate(-53.3185619525693deg);
            width: 908px;
            height: 894px;
            position: absolute;
            left: 1045px;
            top: 2240px;
            background-image: url("/images/curves4_4.png");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_569 {
            width: 783px;
            height: 771px;
            position: absolute;
            left: -312px;
            top: -472px;
            background-image: url(/images/curves4_1.png);
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_570 {
            width: 902.1189575195312px;
            height: 45px;
            position: absolute;
            left: 40%;
            top: 40px;
        }

        .e228_571 {
            width: 639.9998779296875px;
            height: 28.97138023376465px;
            position: absolute;
            left: 0px;
            top: 8px;
        }

        .e228_572 {
            color: rgba(0, 0, 0, 1);
            width: 58.18181610107422px;
            height: 21.978288650512695px;
            position: absolute;
            left: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
        }

        .e228_573 {
            color: rgba(0, 0, 0, 1);
            width: 143.29966735839844px;
            height: 28.97138023376465px;
            position: absolute;
            left: 107.744140625px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
            font-weight: bolder;
        }

        .e228_574 {
            color: rgba(0, 0, 0, 1);
            width: 70.0336685180664px;
            height: 28.97138023376465px;
            position: absolute;
            left: 300.60595703125px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
        }

        .e228_575 {
            color: rgba(0, 0, 0, 1);
            width: 104.51177978515625px;
            height: 28.97138023376465px;
            position: absolute;
            left: 420.2020263671875px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
        }

        .e228_576 {
            color: rgba(0, 0, 0, 1);
            width: 65.72390747070312px;
            height: 26.97335433959961px;
            position: absolute;
            left: 574.2760009765625px;
            top: 1px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
        }

        .e228_578 {
            width: 202.1189422607422px;
            height: 45px;
            position: absolute;
            left: 700px;
            top: 0px;
        }

        .e228_579 {
            width: 44.90810012817383px;
            height: 45px;
            position: absolute;
            left: 0px;
            top: 0px;
            border-top-left-radius: 220px;
            border-top-right-radius: 220px;
            border-bottom-left-radius: 220px;
            border-bottom-right-radius: 220px;
            background-image: url("/images/default.png");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_580 {
            width: 142.30056762695312px;
            height: 20.675809860229492px;
            position: absolute;
            left: 59.818359375px;
            top: 2px;
        }

        .e228_581 {
            color: rgba(0, 0, 0, 1);
            width: 142.30056762695312px;
            height: 20.675809860229492px;
            position: absolute;
            left: 0px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 20px;
            letter-spacing: 0;
        }

        .e228_585 {
            width: 1600px;
            height: 191px;
            position: absolute;
            left: 0px;
            top: 1000px;
        }

        .e228_586 {
            box-shadow: 0px 30px 40px rgba(0, 0, 0, 0.10000000149011612);
            background-color: rgba(68.00000354647636, 66.79111361503601, 63.46666820347309, 1);
            opacity: 0.5;
            width: 1600px;
            height: 95px;
            position: absolute;
            top: 95px;
        }

        .e228_587 {
            background-color: rgba(116.00000068545341, 55.00000052154064, 58.00000034272671, 1);
            width: 100%;
            height: 94.90682983398438px;
            position: absolute;
            left: 0px;
            top: 0px;
        }

        .e228_594 {
            width: 353.18548583984375px;
            height: 15%;
            position: absolute;
            left: 142.2223358154297px;
            top: 20%;
        }

        .e228_595 {
            color: #ff005e;;
            height: 15.42236042022705px;
            position: absolute;
            left: 80%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_596 {
            color: #ff005e;;
            height: 15.42236042022705px;
            position: absolute;
            left: 60%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_597 {
            color: #ff005e;;
            height: 15.42236042022705px;
            position: absolute;
            left: 40%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_598 {
            color: #ff005e;;
            height: 15.42236042022705px;
            position: absolute;
            left: 20%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_599 {
            color: #ff005e;;
            height: 15.42236042022705px;
            position: absolute;
            left: 0%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_600 {
            color: rgba(0, 0, 0, 1);
            width: 350.8148193359375px;
            height: 26.09937858581543px;
            position: absolute;
            left: 142.2223358154297px;
            top: 130.496826171875px;
            font-family: Montserrat;
            text-align: left;
            font-size: 14px;
            letter-spacing: 0;
            line-height: 24px;
        }

        .start_quest{
            width: 783px;
            height: 771px;
            position: absolute;
            left: 0px;
            top: 0px;
            background-image: url("images/Group.png");
            background-repeat: no-repeat;
            background-size: cover;
        }
        
        .container{
            width: 90px;
            height: 100px;
            position: absolute;
            top: 30%;
            overflow: hidden;
            left: 10%;
         }

        .container2{
            width: 90px;
            height: 100px;
            position: absolute;
            top: 40%;
            overflow: hidden;
            left: 10%;
        }

        .container3{
            width: 90px;
            height: 100px;
            position: absolute;
            top: 50%;
            overflow: hidden;
            left: 10%;

        }

        .task1{
            filter: drop-shadow(2px 4px 6px white);
            width: 210px;
            height: 60px;
            position: absolute;
            left: 20%;
            top: 31%;
        }
        .task2{
            width: 210px;
            height: 60px;
            position: absolute;
            left: 20%;
            top: 41%;
        }
        .task3{
            width: 210px;
            height: 60px;
            position: absolute;
            left: 20%;
            top: 51%;
        }

        .getTask{
            background-color: rgba(255, 220.00000208616257, 195.0000035762787, 1);
            width: 210px;
            height: 60px;
            position: absolute;
            left: 0px;
            top: 0px;
            border-top-left-radius: 83px;
            border-top-right-radius: 83px;
            border-bottom-left-radius: 83px;
            border-bottom-right-radius: 83px;
            border: hidden;
            font-family: Montserrat;
            text-align: center;
            font-size: 30px;
            letter-spacing: 0;
            cursor: pointer;
        }

        body {
            background: #E5E5E5;
            margin: 0px;
        }

        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            padding-top: 100px; /* Location of the box */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
            background-color: #fefefe;
            margin: auto;
            padding: 20px;
            border: 1px solid #888;
            width: 80%;
        }

        /* The Close Button */
        .close {
            color: #aaaaaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: #000;
            text-decoration: none;
            cursor: pointer;
        }
    </style>

</head>

<body>
<script>
    let modal = document.getElementById("myModal");
    let btn = document.getElementById("GetTask");

    let span = document.getElementsByClassName("close")[0];

    function f1() {
        modal.style.display = "block";
        console.log("clicked");
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
<form method="get" action="/test1">
    <div class=e228_549>
        <div class="e228_550"></div>
        <div class="e228_565"></div>
        <div class="e228_566"></div>
        <div class="e228_567"></div>
        <div class="e228_568"></div>
        <div class="e228_569"></div>
        <div id="myModal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <p>Some text in the Modal..</p>
            </div>

        </div>
        <div class="container">
            <img src="images/Group.png" style="width: 100%" />
        </div>
        <div class="task1">
            <input type="button" onclick="f1()" id="GetTask" class="getTask" value="Get task!">
        </div>
        <div class="container2">
            <img src="images/Group (2).png" style="width: 100%"/>
        </div>
        <div class="task2">
            <input type="button" class="getTask" value="Get task!" style="background-color: lightsteelblue; cursor: default;">
        </div>
        <div class="container3">
            <img src="images/Group (2).png" style="width: 100%"/>
        </div>
        <div class="task3">
            <input type="button" class="getTask" value="Get task!" style="background-color: lightsteelblue; cursor: default;">
        </div>
        <div class=e228_570>
            <div class=e228_571>
                <a href="/user/mainMenu"><span class="e228_572">Home</span></a>
                <span class="e228_573">Achievements</span>
                <a href="/test"><span class="e228_574">Routes</span></a>
                <span class="e228_575">About Us</span>
                <span class="e228_576">EN</span>
            </div>
            <div class=e228_578>
                <div class="e228_579"></div>
                <div class=e228_580>
                    <span class="e228_581">${user.name} ${user.surname}</span>
                </div>
            </div>
        </div>
        <div class=e228_585>
            <div class="e228_586"></div>
            <div class="e228_587"></div>
            <div class=e228_594>
                <span class="e228_595">Contact</span>
                <span class="e228_596">Blog</span>
                <span class="e228_597">About</span>
                <span class="e228_598">Work</span>
                <span class="e228_599">Home</span>
            </div>
            <span class="e228_600">Copyright © 2021 KyivQuest. All rights reserved.</span>
        </div>
    </div>
</form>
</body>
</html>