<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Html Generated</title>
    <meta name="description" content="Figma htmlGenerator">
    <meta name="author" content="htmlGenerator">
    <link href="https://fonts.googleapis.com/css?family=KyivType+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

    <style>
        .e228_549 {
            overflow: hidden;
        }

        .e228_549 {
            width: 100%;
            height: 1190px;
            position: absolute;
        }

        .e228_550 {
            width: 100%;
            height: 2500px;
            position: absolute;
        }

        .e228_551 {
            width: 800px;
            height: 305px;
            position: absolute;
            left: 10%;
            top: 25%;
        }

        .e228_552 {
            width: 800px;
            height: 214px;
            position: absolute;
            left: 0px;
            top: 0px;
        }

        .e228_553 {
            color: rgba(0, 0, 0, 1);
            width: 550px;
            height: 134px;
            position: absolute;
            left: 0px;
            top: 80px;
            font-family: KyivType Sans;
            text-align: left;
            font-size: 22px;
            letter-spacing: 0;
        }

        .e228_554 {
            color: rgba(0, 0, 0, 1);
            width: 800px;
            height: 80px;
            position: absolute;
            left: 0px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 40px;
            letter-spacing: 0;
        }

        .e228_555 {
            width: 210px;
            height: 60px;
            position: absolute;
            left: 0px;
            top: 155px;
        }

        .e228_556 {
            background-color: rgba(0, 0, 0, 1);
            width: 210px;
            height: 60px;
            position: absolute;
            left: 0px;
            top: 0px;
            border-top-left-radius: 83px;
            border-top-right-radius: 83px;
            border-bottom-left-radius: 83px;
            border-bottom-right-radius: 83px;
        }

        .e228_557 {
            color: rgba(124.00000020861626, 177.0000046491623, 198.00000339746475, 1);
            width: 195.40106201171875px;
            height: 40.000003814697266px;
            position: absolute;
            left: 7px;
            top: 10px;
            font-family: Montserrat;
            text-align: center;
            font-size: 30px;
            letter-spacing: 0;
        }

        .e228_558 {
            width: 550px;
            height: 305px;
            position: absolute;
            left: 40%;
            top: 40%;
        }

        .e228_559 {
            height: 214px;
            position: absolute;
            left: 0px;
            top: 0px;
        }

        .e228_560 {
            color: rgba(0, 0, 0, 1);
            width: 550px;
            height: 134px;
            position: absolute;
            left: 30px;
            top: 80px;
            font-family: KyivType Sans;
            text-align: right;
            font-size: 20px;
            letter-spacing: 0;
        }

        .e228_561 {
            color: rgba(0, 0, 0, 1);
            width: 550px;
            height: 80px;
            position: absolute;
            left: 0px;
            top: 0px;
            font-family: Montserrat;
            text-align: right;
            font-size: 40px;
            letter-spacing: 0;
        }

        .e228_562 {
            width: 210px;
            height: 60px;
            position: absolute;
            left: 61%;
            top: 155px;
        }

        .e228_563 {
            background-color: rgba(0, 0, 0, 1);
            width: 210px;
            height: 60px;
            position: absolute;
            left: 0px;
            top: 0px;
            border-top-left-radius: 83px;
            border-top-right-radius: 83px;
            border-bottom-left-radius: 83px;
            border-bottom-right-radius: 83px;
        }

        .e228_564 {
            color: rgba(124.00000020861626, 177.0000046491623, 198.00000339746475, 1);
            width: 195.40106201171875px;
            height: 40.000003814697266px;
            position: absolute;
            left: 7px;
            top: 10px;
            font-family: Montserrat;
            text-align: center;
            font-size: 30px;
            letter-spacing: 0;
        }

        .e228_565 {
            width: 583px;
            height: 574px;
            position: absolute;
            left: -158px;
            top: -318px;
        }

        .e228_566 {
            width: 908px;
            height: 894px;
            position: absolute;
            left: 1185px;
            top: 197px;
            background-image: url("/images/curves4_2.png");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_567 {
            transform: rotate(-164.76853003393214deg);
            width: 908px;
            height: 894px;
            position: absolute;
            left: 350px;
            top: 850px;
            background-image: url("/images/curves4_3.png");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_568 {
            transform: rotate(-53.3185619525693deg);
            width: 908px;
            height: 894px;
            position: absolute;
            left: 1045px;
            top: 2240px;
            background-image: url("/images/curves4_4.png");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_569 {
            width: 783px;
            height: 771px;
            position: absolute;
            left: -312px;
            top: -472px;
            background-image: url(/images/curves4_1.png);
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_570 {
            width: 902.1189575195312px;
            height: 45px;
            position: absolute;
            left: 40%;
            top: 40px;
        }

        .e228_571 {
            width: 639.9998779296875px;
            height: 28.97138023376465px;
            position: absolute;
            left: 0px;
            top: 8px;
        }

        .e228_572 {
            color: rgba(0, 0, 0, 1);
            width: 58.18181610107422px;
            height: 21.978288650512695px;
            position: absolute;
            left: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
        }

        .e228_573 {
            color: rgba(0, 0, 0, 1);
            width: 143.29966735839844px;
            height: 28.97138023376465px;
            position: absolute;
            left: 107.744140625px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
        }

        .e228_574 {
            color: rgba(0, 0, 0, 1);
            width: 70.0336685180664px;
            height: 28.97138023376465px;
            position: absolute;
            left: 300.60595703125px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
            font-weight: bolder;
        }

        .e228_575 {
            color: rgba(0, 0, 0, 1);
            width: 104.51177978515625px;
            height: 28.97138023376465px;
            position: absolute;
            left: 420.2020263671875px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
        }

        .e228_576 {
            color: rgba(0, 0, 0, 1);
            width: 65.72390747070312px;
            height: 26.97335433959961px;
            position: absolute;
            left: 574.2760009765625px;
            top: 1px;
            font-family: Montserrat;
            text-align: left;
            font-size: 18px;
            letter-spacing: 0;
        }

        .e228_578 {
            width: 202.1189422607422px;
            height: 45px;
            position: absolute;
            left: 700px;
            top: 0px;
        }

        .e228_579 {
            width: 44.90810012817383px;
            height: 45px;
            position: absolute;
            left: 0px;
            top: 0px;
            border-top-left-radius: 220px;
            border-top-right-radius: 220px;
            border-bottom-left-radius: 220px;
            border-bottom-right-radius: 220px;
            background-image: url("/images/default.png");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .e228_580 {
            width: 142.30056762695312px;
            height: 20.675809860229492px;
            position: absolute;
            left: 59.818359375px;
            top: 2px;
        }

        .e228_581 {
            color: rgba(0, 0, 0, 1);
            width: 142.30056762695312px;
            height: 20.675809860229492px;
            position: absolute;
            left: 0px;
            top: 0px;
            font-family: Montserrat;
            text-align: left;
            font-size: 20px;
            letter-spacing: 0;
        }

        .e228_585 {
            width: 1600px;
            height: 191px;
            position: absolute;
            left: 0px;
            top: 1000px;
        }

        .e228_586 {
            box-shadow: 0px 30px 40px rgba(0, 0, 0, 0.10000000149011612);
            background-color: rgba(68.00000354647636, 66.79111361503601, 63.46666820347309, 1);
            opacity: 0.5;
            width: 1600px;
            height: 95px;
            position: absolute;
            top: 95px;
        }

        .e228_587 {
            background-color: rgb(97 107 111);
            width: 100%;
            height: 94.90682983398438px;
            position: absolute;
            left: 0px;
            top: 0px;
        }

        .e228_594 {
            width: 353.18548583984375px;
            height: 15%;
            position: absolute;
            left: 142.2223358154297px;
            top: 20%;
        }

        .e228_595 {
            color: rgba(255, 220, 195, 1);
            height: 15.42236042022705px;
            position: absolute;
            left: 80%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_596 {
            color: rgba(255, 220, 195, 1);
            height: 15.42236042022705px;
            position: absolute;
            left: 60%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_597 {
            color: rgba(255, 220, 195, 1);
            height: 15.42236042022705px;
            position: absolute;
            left: 40%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_598 {
            color: rgba(255, 220, 195, 1);
            height: 15.42236042022705px;
            position: absolute;
            left: 20%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_599 {
            color: rgba(255, 220, 195, 1);
            height: 15.42236042022705px;
            position: absolute;
            left: 0%;
            font-family: Montserrat;
            text-align: right;
            font-size: 15px;
            letter-spacing: 0;
        }

        .e228_600 {
            color: rgba(0, 0, 0, 1);
            width: 350.8148193359375px;
            height: 26.09937858581543px;
            position: absolute;
            left: 142.2223358154297px;
            top: 130.496826171875px;
            font-family: Montserrat;
            text-align: left;
            font-size: 14px;
            letter-spacing: 0;
            line-height: 24px;
        }

        .e725_5 {
            width: 100%;
            height: 100%;
            position: absolute;
            left: 2%;
            top: 30%;
        }
        .e732_15 {
            width:359px;
            height:307px;
            position:absolute;
            left:0px;
            top:0px;
        }
        .e725_2 {
            width:359px;
            height:220px;
            position:absolute;
            left:0px;
            top:0px;
            background-image:url(images/lipki.png);
            background-repeat:no-repeat;
            background-size:cover;
        }
        .e732_6 {
            filter: drop-shadow(2px 4px 6px white);
            width:210px;
            height:60px;
            position:absolute;
            left:75px;
            top:245px;
        }
        .e732_7 {
            background-color:rgba(255, 220.00000208616257, 195.0000035762787, 1);
            width:210px;
            height:60px;
            position:absolute;
            left:0px;
            top:0px;
            border-top-left-radius:83px;
            border-top-right-radius:83px;
            border-bottom-left-radius:83px;
            border-bottom-right-radius:83px;
            border: hidden;
            font-family:Montserrat;
            text-align:center;
            font-size:30px;
            letter-spacing:0;
            cursor: pointer;
        }

        .e732_16 {
            width:359px;
            height:306px;
            position:absolute;
            left:550px;
            top:1px;
        }
        .e725_3 {
            width:359px;
            height:220px;
            position:absolute;
            left:0px;
            top:0px;
            background-image:url(images/park.png);
            background-repeat:no-repeat;
            background-size:cover;
        }
        .e732_9 {
            filter: drop-shadow(2px 4px 6px white);
            width:210px;
            height:60px;
            position:absolute;
            left:75px;
            top:245px;
        }
        .e732_10 {
            background-color:rgba(255, 220.00000208616257, 195.0000035762787, 1);
            width:210px;
            height:60px;
            position:absolute;
            left:0px;
            top:0px;
            border-top-left-radius:83px;
            border-top-right-radius:83px;
            border-bottom-left-radius:83px;
            border-bottom-right-radius:83px;
        }
        .e732_11 {
             color:rgba(0, 0, 0, 1);
             width:195.40106201171875px;
             height:40.000003814697266px;
             position:absolute;
             left:7px;
             top:10px;
             font-family:Montserrat;
             text-align:center;
             font-size:30px;
             letter-spacing:0;
         }
        .e732_17 {
            width:358px;
            height:326px;
            position:absolute;
            left:1100px;
            top:1px;
        }
        .e725_4 {
            width:358px;
            height:220px;
            position:absolute;
            left:0px;
            top:0px;
            background-image:url(images/vozd.png);
            background-repeat:no-repeat;
            background-size:cover;
        }
        .e732_12 {
            filter: drop-shadow(2px 4px 6px white);
            width:210px;
            height:60px;
            position:absolute;
            left:74px;
            top:245px;
        }
        .e732_13 {
            background-color:rgba(255, 220.00000208616257, 195.0000035762787, 1);
            width:210px;
            height:60px;
            position:absolute;
            left:0px;
            top:0px;
            border-top-left-radius:83px;
            border-top-right-radius:83px;
            border-bottom-left-radius:83px;
            border-bottom-right-radius:83px;
        }
        .e732_14 {
            color:rgba(0, 0, 0, 1);
            width:195.40106201171875px;
            height:40.000003814697266px;
            position:absolute;
            left:7px;
            top:10px;
            font-family:Montserrat;
            text-align:center;
            font-size:30px;
            letter-spacing:0;
        }

        body {
            background: #E5E5E5;
            margin: 0px;
        }
    </style>

</head>

<body>
<form method="post" action="/test">
    <div class=e228_549>
        <div class="e228_550"></div>
        <div class="e228_565"></div>
        <div class="e228_566"></div>
        <div class="e228_567"></div>
        <div class="e228_568"></div>
        <div class="e228_569"></div>
        <div class=e228_570>
            <div class=e228_571>
                <a href="/user/mainMenu"><span class="e228_572">Home</span></a>
                <span class="e228_573">Achievements</span>
                <a href="/user/routeChoice"><span class="e228_574">Routes</span></a>
                <span class="e228_575">About Us</span>
                <span class="e228_576">EN</span>
            </div>
            <div class=e228_578>
                <div class="e228_579"></div>
                <div class=e228_580>
                    <span class="e228_581">${user.name} ${user.surname}</span>
                </div>
            </div>
        </div>
        <div class="e725_5">
            <div class="e732_15">
                <div class="e725_2"></div>
                <div class="e732_6">
                    <input type="submit" name="lipki" value="Start" class="e732_7">
<#--                    <span class="e732_8">Start</span>-->
                </div>
            </div>
            <div class="e732_16">
                <div class="e725_3"></div>
                <div class="e732_9">
                    <div class="e732_10"></div>
                    <span class="e732_11">Start</span>
                </div>
            </div>
            <div class="e732_17">
                <div class="e725_4"></div>
                <div class="e732_12">
                    <div class="e732_13"></div>
                    <span class="e732_14">Start</span></div>
            </div>
        </div>
        <div class=e228_585>
            <div class="e228_586"></div>
            <div class="e228_587"></div>
            <div class=e228_594>
                <span class="e228_595">Contact</span>
                <span class="e228_596">Blog</span>
                <span class="e228_597">About</span>
                <span class="e228_598">Work</span>
                <span class="e228_599">Home</span>
            </div>
            <span class="e228_600">Copyright © 2021 KyivQuest. All rights reserved.</span>
        </div>
    </div>
</form>
</body>
</html>